"""Ensure pyproject.toml, uv.lock, and requirements.txt stay a single source of truth.

Manual edits to ``requirements.txt`` or drift from the lockfile break reproducible installs.
This module runs ``uv lock --check`` and compares ``requirements.txt`` to ``uv export``.
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def _normalize_uv_export_text(text: str) -> str:
    """Normalize uv export output for stable comparison (header path, optional --frozen)."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = text.splitlines()
    if len(lines) >= 2 and lines[0].startswith("# This file was autogenerated by uv"):
        lines[1] = "#    uv export --no-emit-package pyproject.toml -o requirements.txt"
    return "\n".join(lines) + "\n"


def test_uv_lock_matches_pyproject() -> None:
    r = subprocess.run(
        ["uv", "lock", "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert r.returncode == 0, (
        "uv.lock is out of date vs pyproject.toml; run: uv lock\n"
        f"{r.stdout}\n{r.stderr}"
    )


def test_requirements_txt_matches_uv_export() -> None:
    committed = (REPO_ROOT / "requirements.txt").read_text(encoding="utf-8")
    with tempfile.NamedTemporaryFile(
        suffix="-requirements-from-uv.txt",
        delete=False,
    ) as tmp:
        tmp_path = Path(tmp.name)
    try:
        subprocess.run(
            [
                "uv",
                "export",
                "--frozen",
                "--no-emit-package",
                "pyproject.toml",
                "-o",
                str(tmp_path),
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        fresh = tmp_path.read_text(encoding="utf-8")
    finally:
        tmp_path.unlink(missing_ok=True)

    assert _normalize_uv_export_text(committed) == _normalize_uv_export_text(fresh), (
        "requirements.txt does not match `uv export` from the lockfile. "
        "Regenerate: uv export --no-emit-package pyproject.toml -o requirements.txt "
        "(after uv lock if you changed pyproject.toml)."
    )
