---
# Baseline "operator workstation" packages. Keep conservative and common.
t14_baseline_packages:
  - ca-certificates
  - procps
  - curl
  - git
  - gnupg
  - openssh-client
  - openssh-server
  - wget
  - auditd
  - audispd-plugins
  - aide
  - debsums
  - needrestart
  - dlocate
  - lsof
  - lm-sensors
  - htop
  - btop
  - ncdu
  - tree
  - pydf
  - lnav
  - multitail
  - sqlite3

