---
- name: Ensure etckeeper package is installed
  ansible.builtin.apt:
    name: etckeeper
    state: present
    update_cache: false

- name: Ensure etckeeper is initialized (best-effort)
  when: t14_etckeeper_enable | bool
  ansible.builtin.command: etckeeper init
  args:
    creates: /etc/.git
  failed_when: false

