"""One-off generator for api/locales/en.json and pt-BR.json (identical key trees).

Warning: ``_en()`` / ``_pt_br()`` must stay in sync with all template ``t('…')`` keys.
Do not run this script to refresh a single string unless those dicts include every
namespace (e.g. ``assessment``); otherwise prefer editing ``en.json`` / ``pt-BR.json``
directly for small copy changes.
"""

from __future__ import annotations

import json
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_LOCALES = _REPO / "api" / "locales"


def _en() -> dict:
    return {
        "nav": {
            "dashboard": "Dashboard (dashBOARd)",
            "reports": "Reports",
            "config": "Configuration",
            "help": "Help & Docs",
            "about": "About",
            "locale_en": "English",
            "locale_pt": "Portuguese (Brazil)",
        },
        "banner": {
            "insecure_title": "Plaintext HTTP",
            "insecure_body": (
                "this dashboard is not using TLS. Traffic can be read or modified on the network path. "
                "Use --https-cert-file / --https-key-file or terminate TLS on a reverse proxy. "
                "See GET /status (dashboard_transport)."
            ),
            "gov_title": "Governance / trust",
            "gov_body": (
                "severity {severity} (license {license_state}). "
                "Global API key surface: {mode}. "
                "Optional per-route RBAC (api.rbac, Pro+ dashboard_rbac) — see GET /status "
                "(enterprise_surface.access_surface.rbac)."
            ),
        },
        "meta": {"title_suffix": "Data Boar"},
        "dashboard": {
            "page_title": "Dashboard — Data Boar",
            "h1": "Audit Dashboard",
            "license_h2": "License status",
            "scan_h2": "Scan status",
            "state": "State:",
            "running": "Running",
            "idle": "Idle",
            "current_session": "Current session:",
            "findings_run": "Findings this run:",
            "tenant_label": "Customer / tenant name (optional)",
            "tenant_ph": "e.g. Acme Corp",
            "tech_label": "Technician / operator (optional)",
            "tech_ph": "e.g. João Silva",
            "cli_parity": "CLI parity for one-shot scans:",
            "cli_parity_link": "Help & Docs",
            "cli_parity_tail": (
                "From the CLI (--scan-compressed, --content-type-check, --jurisdiction-hint)."
            ),
            "scan_compressed": "Also scan inside compressed files (zip, tar, 7z, …)",
            "scan_compressed_hint": (
                "May significantly increase run time and I/O. Use only when you need to inspect "
                "contents of archives."
            ),
            "content_type": "Use content-type detection (magic bytes) for file format",
            "content_type_hint": (
                "Helps find renamed or cloaked files (e.g. PDF saved as .txt). Reads the start of "
                "each file—may increase I/O and run time."
            ),
            "jurisdiction": "Heuristic jurisdiction hints (Report info — DPO / counsel)",
            "jurisdiction_hint": (
                "Optional notes when metadata may suggest CCPA/CPRA, Colorado, or Japan APPI scope. "
                "Not a legal conclusion; configure report.jurisdiction_hints for defaults."
            ),
            "start_scan": "Start scan",
            "discovery_h2": "Data discovery (last run)",
            "stat_db": "Database findings",
            "stat_fs": "Filesystem findings",
            "stat_fail": "Scan failures",
            "stat_total": "Total findings",
            "session_line": "Session:",
            "tenant_kv": "Tenant:",
            "tech_kv": "Technician:",
            "chart_h2": "Progress over time",
            "chart_intro": "Total findings and risk score (0–100) per scan, in chronological order.",
            "chart_empty": "Run at least one scan to see the progress graph.",
            "chart_aria": "Findings and score over sequential scans",
            "sessions_h2": "Recent sessions",
            "view_reports": "View all reports",
            "th_session": "Session",
            "th_started": "Started",
            "th_tenant": "Tenant / Customer",
            "th_technician": "Technician / Operator",
            "th_db": "DB",
            "th_fs": "FS",
            "th_failures": "Failures",
            "th_report": "Report",
            "download": "Download",
            "no_sessions_row": "No sessions yet. Start a scan.",
            "about_app_h2": "About this application",
            "about_app_p": (
                "Reports (Excel and heatmap) and this dashboard are generated by this application; "
                "see About for full details."
            ),
            "about_link": "About",
        },
        "config": {
            "page_title": "Configuration — Data Boar",
            "h1": "Scan configuration",
            "intro": "Edit the audit configuration (YAML). Saved file:",
            "intro_tail": "Changes apply to the next scan.",
            "error_prefix": "Error:",
            "no_yaml_error": "No YAML content provided.",
            "saved_ok": "Configuration saved successfully.",
            "yaml_label": "YAML configuration",
            "save": "Save configuration",
            "readme_blurb": (
                "See README and docs/USAGE.md for target types "
                "(database, filesystem, api, powerbi, dataverse, shares) and options."
            ),
        },
        "reports": {
            "page_title": "Reports — Data Boar",
            "h1": "Reports",
            "intro": (
                "Download Excel reports (and heatmap) for each scan session. "
                "“Download” regenerates the report for that session."
            ),
            "sort_newest": "Newest first",
            "sort_oldest": "Oldest first",
            "order_label": "Order by date:",
            "th_session": "Session ID",
            "th_started": "Started",
            "th_finished": "Finished",
            "th_status": "Status",
            "th_tenant": "Tenant / Customer",
            "th_technician": "Technician / Operator",
            "th_db": "DB findings",
            "th_fs": "FS findings",
            "th_failures": "Failures",
            "th_report": "Report",
            "download": "Download",
            "no_sessions": "No sessions yet. Run a scan from the",
            "dashboard_link": "dashboard",
        },
        "about": {
            "page_title": "About — Data Boar (dashBOARd)",
            "h1": "About",
            "dashmuted": "(dashBOARd)",
            "app_h2": "Application",
            "web_dash": "Web dashboard experience:",
            "author_h2": "Author",
            "license_h2": "Subscription / runtime license status",
            "license_intro": (
                "Operational status of optional commercial enforcement (default: open distribution). "
                "See docs/LICENSING_SPEC.md."
            ),
            "state": "State:",
            "mode": "Mode:",
            "licensed_customer": "Licensed customer (token):",
            "expires": "Expiration (UTC):",
            "issuer": "Issuer (token):",
        },
        "help": {
            "page_title": "Help & Docs — Data Boar",
            "h1": "Help & documentation",
            "what_h2": "What this app does",
            "what_p1": (
                "This application scans configured data sources (databases, filesystems, APIs and shares) "
                "for personal and sensitive data, stores only metadata in a local SQLite database, "
                "and generates Excel reports plus a sensitivity/risk heatmap PNG."
            ),
            "what_p2": (
                "Each run is a scan session with optional tenant / customer and technician / operator "
                "tags, so you can attribute results."
            ),
            "run_h2": "How to run a scan",
            "run_web_h3": "From the web dashboard",
            "run_web_li1": "Go to the Dashboard page.",
            "run_web_li2": (
                "Ensure your Configuration (see Config page) has the desired targets "
                "(databases, filesystems, APIs, etc.). The scan will run exactly those targets."
            ),
            "run_web_li3": "(Optional) Fill in Customer / tenant and Technician / operator.",
            "run_web_li4": (
                "Click Start scan. This triggers a full audit of all targets in the current config. "
                "The status panel will update and the page will auto-refresh when the run finishes."
            ),
            "run_web_tail": (
                "Recent sessions are listed at the bottom of the dashboard and on the Reports page, "
                "with download links."
            ),
            "run_cli_h3": "From the CLI",
            "run_cli_p1": (
                "From the repo root, prefer uv run python main.py (or activate your venv and run "
                "python main.py). Full flag list: python main.py --help. Packaged installs: "
                "man 1 data_boar (command) and man 5 data_boar (config file format)."
            ),
            "run_cli_oneshot": "One-shot audit (same targets as a dashboard scan):",
            "run_cli_api": "Start the API / dashBOARd (no scan until you use the browser or HTTP):",
            "run_cli_tls": (
                "You must either terminate TLS at the process (--https-cert-file + --https-key-file, "
                "or the same under api: in config) or explicitly accept plaintext with "
                "--allow-insecure-http (or api.allow_insecure_http: true). The official Docker image "
                "passes --allow-insecure-http by default; mount certs and remove it for HTTPS."
            ),
            "run_cli_bind": (
                "Bind order when using --web: --host overrides api.host in config and API_HOST; "
                "if none are set, the default is 127.0.0.1 (Docker image often sets API_HOST=0.0.0.0). "
                "Port: api.port in config vs --port. Transport: GET /status and GET /health include "
                "dashboard_transport — see docs/USAGE.md."
            ),
            "run_cli_danger": (
                "Dangerous maintenance (lab/demo only): --reset-data wipes SQLite sessions/findings "
                "and deletes generated reports under report.output_dir. See SECURITY.md before using "
                "in production."
            ),
            "run_cli_audit": (
                "Audit trail export (CLI only): --export-audit-trail or --export-audit-trail path.json "
                "writes a JSON snapshot (wipe log, session summary; future: integrity rows). "
                "Does not modify the database. Omit the path or use - for stdout."
            ),
            "dl_h2": "Downloading reports, heatmaps and logs",
            "dl_li1": (
                "Use the Reports page to see all sessions and click Download to get the Excel report "
                "for a specific run."
            ),
            "dl_li2_intro": "Use the API to script downloads:",
            "cfg_h2": "Configuration examples",
            "cfg_p1": (
                "The configuration file (YAML or JSON) defines which targets are scanned. "
                "Minimal YAML example:"
            ),
            "cfg_tail": (
                "Place this file alongside the application (default name config.yaml) or set the "
                "CONFIG_PATH environment variable to point to a different location."
            ),
            "rate_h2": "Rate limiting & safety",
            "rate_p1": (
                "To avoid accidental overload (for example, many scans triggered in a row or too "
                "many sessions in parallel via the API/dashboard), you can enable a rate_limit block "
                "in the main config:"
            ),
            "rate_tail": (
                "When enabled, API endpoints that start scans may return HTTP 429 with a JSON body "
                "indicating why the request was rate-limited (too many running scans, or minimum "
                "interval not elapsed). The CLI only prints warnings using the same rules. "
                "See docs/USAGE.md (EN), docs/USAGE.pt_BR.md (pt-BR) and docs/data_boar.5 for details."
            ),
            "sense_h2": "Sensitivity detection and reporting",
            "sense_p1": (
                "The app detects personal and sensitive data using regex, ML (TF-IDF + classifier), "
                "and optional DL (sentence embeddings). Out-of-the-box it recognises PII (CPF, email, "
                "phone, etc.) and sensitive categories (health, religion, political affiliation, "
                "gender, biometric, genetic, race, union, PEP, sex life). You can:"
            ),
            "sense_li1": (
                "Add your own terms via ml_patterns_file or sensitivity_detection.ml_terms in config."
            ),
            "sense_li2": (
                "Use the example file docs/sensitivity_terms_sensitive_categories.example.yaml and set "
                "ml_patterns_file (or dl_patterns_file) to it."
            ),
            "sense_li3": (
                "Customise the Recommendations sheet with report.recommendation_overrides: map "
                "norm_tag patterns (e.g. health, religious, political) to Base legal, Risk, Priority, "
                "and “Relevante para”."
            ),
            "sense_tail": (
                "See docs/SENSITIVITY_DETECTION.md (EN) and docs/SENSITIVITY_DETECTION.pt_BR.md (pt-BR); "
                "docs/plans/completed/PLAN_SENSITIVE_CATEGORIES_ML_DL.md for design; docs/USAGE.md (EN) "
                "and docs/USAGE.pt_BR.md (pt-BR) for full recommendation_overrides examples."
            ),
            "sec_h2": "Security headers and hardening",
            "sec_p1": (
                "The API and dashboard send security headers on every response (Content-Security-Policy, "
                "X-Frame-Options, Referrer-Policy, Permissions-Policy, HSTS when HTTPS). For deployment "
                "hardening (Docker, Kubernetes, non-root, NetworkPolicy, reverse proxy), see:"
            ),
            "sec_li1": "SECURITY.md – HTTP security headers and optional API key",
            "sec_li2": 'docs/deploy/DEPLOY.md – section "Security and hardening (optional)"',
            "sec_h3": "What to keep an eye out for (technicians)",
            "sec_t1": (
                "Passwords with special characters: Database and MongoDB passwords containing @, :, / "
                "or # are supported; the app encodes them in connection URLs automatically."
            ),
            "sec_t2": (
                "Protecting the Configuration page: The config file may contain credentials. If the API "
                "is exposed to untrusted users or networks, set api.require_api_key: true and use a "
                "strong API key so only authenticated requests can access /config."
            ),
            "sec_t3": (
                "Deployment: Run behind a reverse proxy with TLS when the dashboard or API is exposed "
                "to the internet; use the optional API key and rate limiting as an extra layer."
            ),
            "sec_tail": (
                "For a full list of security fixes, regression tests, and recommendations, see "
                "docs/SECURITY.md (EN) and docs/SECURITY.pt_BR.md (pt-BR)."
            ),
            "more_h2": "More documentation",
            "more_p1": (
                "For full details, including optional connectors (Power BI, Dataverse, REST APIs, shares) "
                "and advanced tuning, see:"
            ),
            "more_li1": (
                "README.md and docs/USAGE.md (English) · docs/USAGE.pt_BR.md (Português – Brasil)"
            ),
            "more_li2": (
                "docs/SENSITIVITY_DETECTION.md (EN) · docs/SENSITIVITY_DETECTION.pt_BR.md (pt-BR) – "
                "ML/DL terms and config"
            ),
            "more_li3": (
                "docs/plans/completed/PLAN_SENSITIVE_CATEGORIES_ML_DL.md – sensitive categories "
                "(health, religion, political, etc.)"
            ),
            "more_tail": (
                "These files live in the project repository and should be kept in sync with the "
                "behaviour you see here."
            ),
        },
        "js": {
            "chart_total": "Total findings",
            "chart_risk": "Risk score (0–100)",
            "chart_y_total": "Total findings",
            "chart_y_risk": "Risk score",
            "status_running": "Running",
            "status_idle": "Idle",
            "starting": "Starting…",
            "started_prefix": "Started:",
            "err_scan_progress": "Scan already in progress.",
            "err_scan_progress_guide": (
                "Wait for the current scan to finish, or restart the API if it is stuck."
            ),
            "err_rate": "Rate limited; try again shortly.",
            "err_rate_guide": (
                "Wait and try again, or adjust rate_limit.max_concurrent_scans and "
                "min_interval_seconds in config."
            ),
            "err_auth": "Not authorized ({code}).",
            "err_auth_guide": (
                "Check API key or auth configuration if the API is protected."
            ),
            "err_network_guide": (
                "Request did not reach the server. Check network, CORS, or ad-blockers; "
                "ensure the API is running."
            ),
            "err_server_guide": "Server error. Check API logs and try again.",
            "err_what": "What to do:",
            "err_prefix": "Error:",
            "retry_after": "Retry after {n} seconds, or adjust rate_limit in config.",
        },
    }


def _pt_br(en: dict) -> dict:
    """Brazilian Portuguese: same structure; technical tokens (--web, paths) preserved where needed."""

    def tr(d: dict) -> dict:
        out: dict = {}
        for k, v in d.items():
            if isinstance(v, dict):
                out[k] = tr(v)
            else:
                out[k] = v
        return out

    base = tr(en)
    base["nav"]["dashboard"] = "Painel (dashBOARd)"
    base["nav"]["reports"] = "Relatórios"
    base["nav"]["config"] = "Configuração"
    base["nav"]["help"] = "Ajuda e documentação"
    base["nav"]["about"] = "Sobre"
    base["nav"]["locale_en"] = "Inglês"
    base["nav"]["locale_pt"] = "Português (Brasil)"
    base["banner"]["insecure_title"] = "HTTP em texto claro"
    base["banner"]["insecure_body"] = (
        "este painel não está usando TLS. O tráfego pode ser lido ou alterado no caminho da rede. "
        "Use --https-cert-file / --https-key-file ou termine TLS em um proxy reverso. "
        "Veja GET /status (dashboard_transport)."
    )
    base["banner"]["gov_title"] = "Governança / confiança"
    base["banner"]["gov_body"] = (
        "severidade {severity} (licença {license_state}). "
        "Superfície de API key global: {mode}. "
        "RBAC por rota opcional (api.rbac, Pro+ dashboard_rbac) — veja GET /status "
        "(enterprise_surface.access_surface.rbac)."
    )
    base["meta"]["title_suffix"] = "Data Boar"
    base["dashboard"]["page_title"] = "Painel — Data Boar"
    base["dashboard"]["h1"] = "Painel de auditoria"
    base["dashboard"]["license_h2"] = "Status da licença"
    base["dashboard"]["scan_h2"] = "Status da varredura"
    base["dashboard"]["state"] = "Estado:"
    base["dashboard"]["running"] = "Em execução"
    base["dashboard"]["idle"] = "Ocioso"
    base["dashboard"]["current_session"] = "Sessão atual:"
    base["dashboard"]["findings_run"] = "Achados nesta execução:"
    base["dashboard"]["tenant_label"] = "Cliente / tenant (opcional)"
    base["dashboard"]["tenant_ph"] = "ex.: Acme Corp"
    base["dashboard"]["tech_label"] = "Técnico / operador (opcional)"
    base["dashboard"]["tech_ph"] = "ex.: João Silva"
    base["dashboard"]["cli_parity"] = "Paridade com a CLI para varreduras pontuais:"
    base["dashboard"]["cli_parity_link"] = "Ajuda e documentação"
    base["dashboard"]["cli_parity_tail"] = (
        "Da CLI (--scan-compressed, --content-type-check, --jurisdiction-hint)."
    )
    base["dashboard"]["scan_compressed"] = (
        "Também varrer dentro de arquivos compactados (zip, tar, 7z, …)"
    )
    base["dashboard"]["scan_compressed_hint"] = (
        "Pode aumentar bastante o tempo de execução e E/S. Use só quando precisar inspecionar "
        "conteúdo de arquivos."
    )
    base["dashboard"]["content_type"] = (
        "Usar detecção de tipo de conteúdo (magic bytes) para o formato do arquivo"
    )
    base["dashboard"]["content_type_hint"] = (
        "Ajuda a encontrar arquivos renomeados ou disfarçados (ex.: PDF salvo como .txt). "
        "Lê o início de cada arquivo — pode aumentar E/S e tempo de execução."
    )
    base["dashboard"]["jurisdiction"] = (
        "Dicas heurísticas de jurisdição (informações do relatório — DPO / jurídico)"
    )
    base["dashboard"]["jurisdiction_hint"] = (
        "Notas opcionais quando metadados podem sugerir escopo CCPA/CPRA, Colorado ou APPI do Japão. "
        "Não é conclusão jurídica; configure report.jurisdiction_hints para padrões."
    )
    base["dashboard"]["start_scan"] = "Iniciar varredura"
    base["dashboard"]["discovery_h2"] = "Descoberta de dados (última execução)"
    base["dashboard"]["stat_db"] = "Achados em banco"
    base["dashboard"]["stat_fs"] = "Achados em sistema de arquivos"
    base["dashboard"]["stat_fail"] = "Falhas na varredura"
    base["dashboard"]["stat_total"] = "Total de achados"
    base["dashboard"]["session_line"] = "Sessão:"
    base["dashboard"]["tenant_kv"] = "Tenant:"
    base["dashboard"]["tech_kv"] = "Técnico:"
    base["dashboard"]["chart_h2"] = "Progresso ao longo do tempo"
    base["dashboard"]["chart_intro"] = (
        "Total de achados e pontuação de risco (0–100) por varredura, em ordem cronológica."
    )
    base["dashboard"]["chart_empty"] = (
        "Execute pelo menos uma varredura para ver o gráfico."
    )
    base["dashboard"]["chart_aria"] = (
        "Achados e pontuação ao longo das varreduras sequenciais"
    )
    base["dashboard"]["sessions_h2"] = "Sessões recentes"
    base["dashboard"]["view_reports"] = "Ver todos os relatórios"
    base["dashboard"]["th_session"] = "Sessão"
    base["dashboard"]["th_started"] = "Início"
    base["dashboard"]["th_tenant"] = "Cliente / tenant"
    base["dashboard"]["th_technician"] = "Técnico / operador"
    base["dashboard"]["th_db"] = "BD"
    base["dashboard"]["th_fs"] = "FS"
    base["dashboard"]["th_failures"] = "Falhas"
    base["dashboard"]["th_report"] = "Relatório"
    base["dashboard"]["download"] = "Baixar"
    base["dashboard"]["no_sessions_row"] = "Nenhuma sessão ainda. Inicie uma varredura."
    base["dashboard"]["about_app_h2"] = "Sobre esta aplicação"
    base["dashboard"]["about_app_p"] = (
        "Relatórios (Excel e mapa de calor) e este painel são gerados por esta aplicação; "
        "veja Sobre para detalhes."
    )
    base["dashboard"]["about_link"] = "Sobre"
    base["config"]["page_title"] = "Configuração — Data Boar"
    base["config"]["h1"] = "Configuração da varredura"
    base["config"]["intro"] = "Edite a configuração de auditoria (YAML). Arquivo salvo:"
    base["config"]["intro_tail"] = "As alterações valem para a próxima varredura."
    base["config"]["error_prefix"] = "Erro:"
    base["config"]["no_yaml_error"] = "Nenhum conteúdo YAML enviado."
    base["config"]["saved_ok"] = "Configuração salva com sucesso."
    base["config"]["yaml_label"] = "Configuração YAML"
    base["config"]["save"] = "Salvar configuração"
    base["config"]["readme_blurb"] = (
        "Veja README e docs/USAGE.md para tipos de alvo "
        "(banco, sistema de arquivos, api, powerbi, dataverse, compartilhamentos) e opções."
    )
    base["reports"]["page_title"] = "Relatórios — Data Boar"
    base["reports"]["h1"] = "Relatórios"
    base["reports"]["intro"] = (
        "Baixe relatórios Excel (e mapa de calor) para cada sessão de varredura. "
        "“Baixar” regenera o relatório dessa sessão."
    )
    base["reports"]["sort_newest"] = "Mais recentes primeiro"
    base["reports"]["sort_oldest"] = "Mais antigos primeiro"
    base["reports"]["order_label"] = "Ordenar por data:"
    base["reports"]["th_session"] = "ID da sessão"
    base["reports"]["th_started"] = "Início"
    base["reports"]["th_finished"] = "Término"
    base["reports"]["th_status"] = "Status"
    base["reports"]["th_tenant"] = "Cliente / tenant"
    base["reports"]["th_technician"] = "Técnico / operador"
    base["reports"]["th_db"] = "Achados BD"
    base["reports"]["th_fs"] = "Achados FS"
    base["reports"]["th_failures"] = "Falhas"
    base["reports"]["th_report"] = "Relatório"
    base["reports"]["download"] = "Baixar"
    base["reports"]["no_sessions"] = (
        "Nenhuma sessão ainda. Execute uma varredura a partir do"
    )
    base["reports"]["dashboard_link"] = "painel"
    base["about"]["page_title"] = "Sobre — Data Boar (dashBOARd)"
    base["about"]["h1"] = "Sobre"
    base["about"]["app_h2"] = "Aplicação"
    base["about"]["web_dash"] = "Experiência do painel web:"
    base["about"]["author_h2"] = "Autor"
    base["about"]["license_h2"] = "Status da licença / assinatura em tempo de execução"
    base["about"]["license_intro"] = (
        "Status operacional do enforcement comercial opcional (padrão: distribuição aberta). "
        "Veja docs/LICENSING_SPEC.md."
    )
    base["about"]["state"] = "Estado:"
    base["about"]["mode"] = "Modo:"
    base["about"]["licensed_customer"] = "Cliente licenciado (token):"
    base["about"]["expires"] = "Expiração (UTC):"
    base["about"]["issuer"] = "Emissor (token):"
    base["help"]["page_title"] = "Ajuda e documentação — Data Boar"
    base["help"]["h1"] = "Ajuda e documentação"
    base["help"]["what_h2"] = "O que esta aplicação faz"
    base["help"]["what_p1"] = (
        "Esta aplicação varre fontes de dados configuradas (bancos, sistemas de arquivos, APIs e "
        "compartilhamentos) em busca de dados pessoais e sensíveis, armazena apenas metadados em "
        "um SQLite local e gera relatórios Excel mais um PNG de mapa de calor sensibilidade/risco."
    )
    base["help"]["what_p2"] = (
        "Cada execução é uma sessão de varredura com tags opcionais de tenant/cliente e "
        "técnico/operador para atribuir resultados."
    )
    base["help"]["run_h2"] = "Como executar uma varredura"
    base["help"]["run_web_h3"] = "Pelo painel web"
    base["help"]["run_web_li1"] = "Abra a página Painel."
    base["help"]["run_web_li2"] = (
        "Garanta que sua Configuração (veja a página Config) tenha os alvos desejados "
        "(bancos, sistemas de arquivos, APIs etc.). A varredura usará exatamente esses alvos."
    )
    base["help"]["run_web_li3"] = (
        "(Opcional) Preencha Cliente / tenant e Técnico / operador."
    )
    base["help"]["run_web_li4"] = (
        "Clique em Iniciar varredura. Isso dispara uma auditoria completa de todos os alvos na "
        "configuração atual. O painel de status será atualizado e a página recarrega ao terminar."
    )
    base["help"]["run_web_tail"] = (
        "Sessões recentes aparecem no fim do painel e na página Relatórios, com links para download."
    )
    base["help"]["run_cli_h3"] = "Pela CLI"
    base["help"]["run_cli_p1"] = (
        "Na raiz do repositório, prefira uv run python main.py (ou ative o venv e execute "
        "python main.py). Lista completa de flags: python main.py --help. Instalações empacotadas: "
        "man 1 data_boar (comando) e man 5 data_boar (formato do arquivo de configuração)."
    )
    base["help"]["run_cli_oneshot"] = (
        "Auditoria pontual (mesmos alvos que uma varredura pelo painel):"
    )
    base["help"]["run_cli_api"] = (
        "Subir a API / dashBOARd (sem varredura até usar o navegador ou HTTP):"
    )
    base["help"]["run_cli_tls"] = (
        "É preciso terminar TLS no processo (--https-cert-file + --https-key-file, ou o mesmo em "
        "api: na config) ou aceitar explicitamente texto claro com --allow-insecure-http (ou "
        "api.allow_insecure_http: true). A imagem Docker oficial passa --allow-insecure-http por "
        "padrão; monte certificados e remova para HTTPS."
    )
    base["help"]["run_cli_bind"] = (
        "Ordem de bind com --web: --host sobrescreve api.host na config e API_HOST; se nada estiver "
        "definido, o padrão é 127.0.0.1 (a imagem Docker costuma definir API_HOST=0.0.0.0). "
        "Porta: api.port na config vs --port. Transporte: GET /status e GET /health incluem "
        "dashboard_transport — veja docs/USAGE.md."
    )
    base["help"]["run_cli_danger"] = (
        "Manutenção perigosa (só lab/demo): --reset-data apaga sessões/achados no SQLite e remove "
        "relatórios gerados em report.output_dir. Veja SECURITY.md antes de usar em produção."
    )
    base["help"]["run_cli_audit"] = (
        "Exportação de trilha de auditoria (só CLI): --export-audit-trail ou "
        "--export-audit-trail caminho.json grava um snapshot JSON (log de wipe, resumo de sessão; "
        "futuro: linhas de integridade). Não modifica o banco. Omita o caminho ou use - para stdout."
    )
    base["help"]["dl_h2"] = "Baixar relatórios, mapas de calor e logs"
    base["help"]["dl_li1"] = (
        "Use a página Relatórios para ver todas as sessões e clique em Baixar para obter o Excel "
        "da execução."
    )
    base["help"]["dl_li2_intro"] = "Use a API para automatizar downloads:"
    base["help"]["cfg_h2"] = "Exemplos de configuração"
    base["help"]["cfg_p1"] = (
        "O arquivo de configuração (YAML ou JSON) define quais alvos são varridos. "
        "Exemplo mínimo em YAML:"
    )
    base["help"]["cfg_tail"] = (
        "Coloque este arquivo junto à aplicação (nome padrão config.yaml) ou defina a variável de "
        "ambiente CONFIG_PATH para outro local."
    )
    base["help"]["rate_h2"] = "Limitação de taxa e segurança"
    base["help"]["rate_p1"] = (
        "Para evitar sobrecarga acidental (por exemplo, muitas varreduras seguidas ou muitas "
        "sessões em paralelo pela API/painel), você pode habilitar um bloco rate_limit na config principal:"
    )
    base["help"]["rate_tail"] = (
        "Quando habilitado, endpoints que iniciam varreduras podem responder HTTP 429 com JSON "
        "explicando o motivo (muitas execuções em paralelo ou intervalo mínimo não atingido). "
        "A CLI só imprime avisos com as mesmas regras. "
        "Veja docs/USAGE.md (EN), docs/USAGE.pt_BR.md (pt-BR) e docs/data_boar.5 para detalhes."
    )
    base["help"]["sense_h2"] = "Detecção de sensibilidade e relatórios"
    base["help"]["sense_p1"] = (
        "A aplicação detecta dados pessoais e sensíveis com regex, ML (TF-IDF + classificador) e "
        "DL opcional (embeddings de frase). Por padrão reconhece PII (CPF, e-mail, telefone etc.) e "
        "categorias sensíveis (saúde, religião, filiação política, gênero, biométrico, genético, raça, "
        "sindical, PEP, vida sexual). Você pode:"
    )
    base["help"]["sense_li1"] = (
        "Adicionar termos via ml_patterns_file ou sensitivity_detection.ml_terms na config."
    )
    base["help"]["sense_li2"] = (
        "Usar o arquivo de exemplo docs/sensitivity_terms_sensitive_categories.example.yaml e "
        "definir ml_patterns_file (ou dl_patterns_file) para ele."
    )
    base["help"]["sense_li3"] = (
        "Personalizar a planilha Recomendações com report.recommendation_overrides: mapeie padrões "
        "norm_tag (ex.: health, religious, political) para Base legal, Risco, Prioridade e "
        "“Relevante para”."
    )
    base["help"]["sense_tail"] = (
        "Veja docs/SENSITIVITY_DETECTION.md (EN) e docs/SENSITIVITY_DETECTION.pt_BR.md (pt-BR); "
        "docs/plans/completed/PLAN_SENSITIVE_CATEGORIES_ML_DL.md para o desenho; docs/USAGE.md (EN) "
        "e docs/USAGE.pt_BR.md (pt-BR) para exemplos completos de recommendation_overrides."
    )
    base["help"]["sec_h2"] = "Cabeçalhos de segurança e endurecimento"
    base["help"]["sec_p1"] = (
        "A API e o painel enviam cabeçalhos de segurança em cada resposta (Content-Security-Policy, "
        "X-Frame-Options, Referrer-Policy, Permissions-Policy, HSTS com HTTPS). Para endurecimento "
        "de implantação (Docker, Kubernetes, não-root, NetworkPolicy, proxy reverso), veja:"
    )
    base["help"]["sec_li1"] = "SECURITY.md – cabeçalhos HTTP e API key opcional"
    base["help"]["sec_li2"] = (
        'docs/deploy/DEPLOY.md – seção "Security and hardening (optional)"'
    )
    base["help"]["sec_h3"] = "O que observar (técnicos)"
    base["help"]["sec_t1"] = (
        "Senhas com caracteres especiais: senhas de banco e MongoDB com @, :, / ou # são suportadas; "
        "a aplicação codifica em URLs de conexão automaticamente."
    )
    base["help"]["sec_t2"] = (
        "Proteger a página de Configuração: o arquivo pode conter credenciais. Se a API estiver "
        "exposta a redes ou usuários não confiáveis, defina api.require_api_key: true e use uma API "
        "key forte para que só requisições autenticadas acessem /config."
    )
    base["help"]["sec_t3"] = (
        "Implantação: execute atrás de proxy reverso com TLS quando o painel ou a API estiverem "
        "expostos à internet; use API key opcional e limitação de taxa como camada extra."
    )
    base["help"]["sec_tail"] = (
        "Para lista completa de correções de segurança, testes de regressão e recomendações, veja "
        "docs/SECURITY.md (EN) e docs/SECURITY.pt_BR.md (pt-BR)."
    )
    base["help"]["more_h2"] = "Mais documentação"
    base["help"]["more_p1"] = (
        "Para detalhes completos, incluindo conectores opcionais (Power BI, Dataverse, APIs REST, "
        "compartilhamentos) e ajustes avançados, veja:"
    )
    base["help"]["more_li1"] = (
        "README.md e docs/USAGE.md (inglês) · docs/USAGE.pt_BR.md (Português – Brasil)"
    )
    base["help"]["more_li2"] = (
        "docs/SENSITIVITY_DETECTION.md (EN) · docs/SENSITIVITY_DETECTION.pt_BR.md (pt-BR) – "
        "termos ML/DL e config"
    )
    base["help"]["more_li3"] = (
        "docs/plans/completed/PLAN_SENSITIVE_CATEGORIES_ML_DL.md – categorias sensíveis "
        "(saúde, religião, política etc.)"
    )
    base["help"]["more_tail"] = (
        "Esses arquivos estão no repositório do projeto e devem refletir o comportamento que você vê aqui."
    )
    base["js"]["chart_total"] = "Total de achados"
    base["js"]["chart_risk"] = "Pontuação de risco (0–100)"
    base["js"]["chart_y_total"] = "Total de achados"
    base["js"]["chart_y_risk"] = "Pontuação de risco"
    base["js"]["status_running"] = "Em execução"
    base["js"]["status_idle"] = "Ocioso"
    base["js"]["starting"] = "Iniciando…"
    base["js"]["started_prefix"] = "Iniciada:"
    base["js"]["err_scan_progress"] = "Já existe uma varredura em andamento."
    base["js"]["err_scan_progress_guide"] = (
        "Aguarde a varredura atual terminar ou reinicie a API se estiver travada."
    )
    base["js"]["err_rate"] = "Limite de taxa; tente novamente em instantes."
    base["js"]["err_rate_guide"] = (
        "Aguarde e tente de novo, ou ajuste rate_limit.max_concurrent_scans e "
        "min_interval_seconds na config."
    )
    base["js"]["err_auth"] = "Não autorizado ({code})."
    base["js"]["err_auth_guide"] = (
        "Verifique API key ou configuração de autenticação se a API estiver protegida."
    )
    base["js"]["err_network_guide"] = (
        "A requisição não chegou ao servidor. Verifique rede, CORS ou bloqueadores; confirme se a API está em execução."
    )
    base["js"]["err_server_guide"] = (
        "Erro no servidor. Verifique os logs da API e tente de novo."
    )
    base["js"]["err_what"] = "O que fazer:"
    base["js"]["err_prefix"] = "Erro:"
    base["js"]["retry_after"] = (
        "Tente após {n} segundos ou ajuste rate_limit na config."
    )
    return base


def main() -> None:
    _LOCALES.mkdir(parents=True, exist_ok=True)
    en = _en()
    pt = _pt_br(en)
    (_LOCALES / "en.json").write_text(
        json.dumps(en, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (_LOCALES / "pt-BR.json").write_text(
        json.dumps(pt, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print("Wrote en.json and pt-BR.json")


if __name__ == "__main__":
    main()
