"""
FastAPI app: dashboard (GET /), config (GET/POST /config), reports list (GET /reports).
API: POST /scan and /start (optional tenant/technician tags), GET /status, /report, /list,
GET /reports/{session_id}, POST /scan_database (optional tenant/technician), PATCH /sessions/{session_id}
and /sessions/{session_id}/technician for metadata updates. On startup load config (config.yaml or CONFIG_PATH)
and create a singleton AuditEngine.

Path safety: session_id is validated before use in file paths. Report paths use
``_real_file_under_out_dir_str`` / ``_resolved_existing_file_under_out_dir``: CodeQL's
documented ``normpath(join(base, filename))`` + ``startswith(base)`` + ``isfile``, with
basename allowlists. Heatmap GET handlers return PNG bytes via ``_heatmap_png_response`` to
avoid ``FileResponse(path=...)`` as an extra sink. See ``tests/test_report_path_safety.py``.

Cache: static assets get long-lived Cache-Control; API/HTML get no-store. Sessions list is cached
in-memory for a short TTL when no scan is running to reduce SQLite reads on repeated dashboard loads.

Security: default middleware adds X-Content-Type-Options, X-Frame-Options, Content-Security-Policy,
Referrer-Policy, Permissions-Policy, and Strict-Transport-Security (only when served over HTTPS).
"""

import os
import re
import time
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path

import yaml
from fastapi import BackgroundTasks, FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel

from core.about import get_about_info
from core.dashboard_transport import get_dashboard_transport_snapshot
from core.host_resolution import effective_api_key_configured
from core.runtime_trust import get_runtime_trust_snapshot


def _about_info() -> dict:
    """Application name, version, author and license (from core.about, matches LICENSE and README)."""
    return get_about_info()


def _template_context(base: dict) -> dict:
    """Merge dashboard transport snapshot into Jinja context (banner, /status parity)."""
    snap = get_dashboard_transport_snapshot()
    ctx = dict(base)
    ctx["dashboard_transport"] = snap
    ctx["show_insecure_banner"] = bool(snap.get("show_insecure_banner"))
    return ctx


# In-memory cache for list_sessions (TTL seconds). Bypassed when a scan is running.
_SESSIONS_CACHE_TTL = 2.0
_sessions_cache: list[dict] | None = None
_sessions_cache_time: float = 0.0

_api_dir = Path(__file__).resolve().parent
templates = Jinja2Templates(directory=str(_api_dir / "templates"))

# Template names (avoid duplicating string literals).
_TEMPLATE_CONFIG = "config.html"

# Session IDs are generated by core.session (e.g. 12 hex + _ + timestamp). Used in path segments.
_SESSION_ID_PATTERN = re.compile(r"^\w{12,64}$", re.ASCII)
_REPORT_FILENAME_PATTERN = re.compile(r"^Relatorio_Auditoria_[A-Za-z0-9_]{4,64}\.xlsx$")
_HEATMAP_FILENAME_PATTERN = re.compile(r"^heatmap_[A-Za-z0-9_]{4,64}\.png$")


def _report_output_dir_resolved(engine) -> Path:
    """Configured ``report.output_dir`` only (never a path derived from report files)."""
    return Path(engine.config.get("report", {}).get("output_dir", ".")).resolve()


def _real_file_under_out_dir_str(out_dir: Path, filename: str) -> str | None:
    """
    Return ``fullpath`` for ``(out_dir / filename)`` if it exists as a file under ``out_dir``.

    Matches CodeQL's documented safe pattern: ``normpath(join(base_path, filename))`` then
    ``fullpath.startswith(base_path)`` with the **same** ``base_path`` string, then
    ``os.path.isfile(fullpath)``. We avoid an extra ``realpath`` between the prefix check
    and file checks so the analyzer's path-injection barrier still applies. ``base_path``
    is ``realpath(abspath(out_dir))`` so the root is canonical.
    """
    if not filename or "/" in filename or "\\" in filename:
        return None
    if filename in (".", "..") or filename.startswith(".."):
        return None
    try:
        base_path = os.path.realpath(os.path.abspath(os.fspath(out_dir)))
    except OSError:
        return None
    fullpath = os.path.normpath(os.path.join(base_path, filename))
    if not fullpath.startswith(base_path):
        return None
    if not os.path.isfile(fullpath):
        return None
    return fullpath


def _resolved_existing_file_under_out_dir(out_dir: Path, filename: str) -> Path | None:
    """``Path`` wrapper for :func:`_real_file_under_out_dir_str` (reports / shared logic)."""
    s = _real_file_under_out_dir_str(out_dir, filename)
    return Path(s) if s else None


def _validated_output_basename(
    path: str | Path, pattern: re.Pattern[str]
) -> str | None:
    """
    Last path segment only, validated against an allowlist pattern.

    Uses ``os.path.basename`` (not ``Path(path)``) so static analysis does not treat
    the stored report path as controlling a path expression before we restrict to
    ``out_dir / basename`` only. ``path`` comes from engine state (last report path),
    not raw HTTP input, but we still normalize to a single filename segment.
    """
    raw = os.fspath(path)
    name = os.path.basename(raw.replace("\\", "/"))
    if not name or pattern.fullmatch(name) is None:
        return None
    return name


def _validate_session_id(session_id: str) -> None:
    """Reject session_id that could be used in path traversal. Raises HTTPException if invalid."""
    if not session_id or not isinstance(session_id, str):
        raise HTTPException(status_code=400, detail="Invalid session_id.")
    if not _SESSION_ID_PATTERN.fullmatch(session_id.strip()):
        raise HTTPException(
            status_code=400,
            detail="Invalid session_id: only alphanumeric and underscore, 12–64 characters.",
        )


def _safe_report_output_path(path: str | Path, engine) -> Path | None:
    """
    Resolve and validate a report/heatmap path against configured report.output_dir.

    Returns the resolved candidate when it is inside output_dir and exists.
    Returns None when missing, invalid, outside output_dir, or non-existent.
    """
    if not path:
        return None
    filename = _validated_output_basename(path, _REPORT_FILENAME_PATTERN)
    if filename is None:
        return None
    return _resolved_existing_file_under_out_dir(
        _report_output_dir_resolved(engine), filename
    )


def _safe_report_path_for_heatmap(engine) -> tuple[Path, str] | None:
    """
    Resolve a report path under ``report.output_dir`` and a session key for heatmap naming.

    Returns ``(safe_report_path, session_key)`` or ``None`` when no report is available.
    """
    path = engine.get_last_report_path()
    sid: str | None = None
    safe_report_path = _safe_report_output_path(path, engine) if path else None
    if not safe_report_path:
        sid = engine.db_manager.current_session_id or None
        if not sid:
            sessions = engine.db_manager.list_sessions()
            if sessions:
                sid = sessions[0]["session_id"]
        if not sid:
            return None
        path = engine.generate_final_reports(sid)
        safe_report_path = _safe_report_output_path(path, engine) if path else None
    if not safe_report_path:
        return None
    if not sid:
        name = safe_report_path.name
        prefix = name.removeprefix("Relatorio_Auditoria_").removesuffix(".xlsx")
        sid = prefix
    return safe_report_path, sid or ""


def _heatmap_png_path_for_download(engine, session_key: str) -> Path | None:
    """
    Resolve ``heatmap_<first 12 chars of session_key>.png`` under configured output_dir.

    Uses only ``engine.config`` for the base directory (not ``report_path.parent``).
    """
    heatmap_filename = f"heatmap_{session_key[:12]}.png"
    if not _HEATMAP_FILENAME_PATTERN.fullmatch(heatmap_filename):
        return None
    return _resolved_existing_file_under_out_dir(
        _report_output_dir_resolved(engine), heatmap_filename
    )


def _heatmap_png_response(engine, session_key: str):
    """
    Heatmap download without ``FileResponse(path=...)`` (CodeQL path sink).

    Opens the file only after :func:`_real_file_under_out_dir_str` (normpath + startswith
    + realpath), matching the documented safe ``open(fullpath)`` pattern.
    """
    from starlette.responses import Response

    heatmap_filename = f"heatmap_{session_key[:12]}.png"
    if not _HEATMAP_FILENAME_PATTERN.fullmatch(heatmap_filename):
        return None
    safe_path = _real_file_under_out_dir_str(
        _report_output_dir_resolved(engine), heatmap_filename
    )
    if not safe_path:
        return None
    try:
        with open(safe_path, "rb") as fh:
            body = fh.read()
    except OSError:
        return None
    fname = os.path.basename(safe_path)
    return Response(
        content=body,
        media_type="image/png",
        headers={"Content-Disposition": f'inline; filename="{fname}"'},
    )


class DatabaseConfig(BaseModel):
    """Single database target for one-off scan via POST /scan_database."""

    name: str
    host: str
    port: int
    user: str
    password: str
    database: str
    driver: str = "postgresql+psycopg2"
    tenant: str | None = None  # optional customer/tenant name for this scan
    technician: str | None = None  # optional technician/operator name for this scan


class ScanStartBody(BaseModel):
    """Optional body for POST /scan: tenant/customer, technician/operator, run-local scan toggles."""

    tenant: str | None = None
    technician: str | None = None
    scan_compressed: bool | None = (
        None  # when True, merge into file_scan for this run only
    )
    content_type_check: bool | None = (
        None  # when True, set file_scan.use_content_type for this run only (magic-byte format sniffing)
    )


# Load config and create engine at import time (or on startup event)
_config_path = os.environ.get("CONFIG_PATH", "config.yaml")
if not Path(_config_path).exists():
    _config_path = "config.yaml"
_config = None
_audit_engine = None


def _get_config_path() -> str:
    """Return path to config file (for dashboard display and save)."""
    return _config_path


def _get_config_raw() -> str:
    """Return raw config file content (YAML) for editing. If file missing, return default YAML."""
    p = Path(_config_path)
    if p.exists():
        return p.read_text(encoding="utf-8")
    return _default_config_yaml()


def _get_config_yaml_for_display() -> str:
    """Return config YAML safe for display: secret values redacted so the UI never shows them."""
    from config.redact_config import redact_config_for_display

    raw = _get_config_raw()
    try:
        data = yaml.safe_load(raw)
        if isinstance(data, dict):
            redacted = redact_config_for_display(data)
            return yaml.dump(
                redacted, default_flow_style=False, allow_unicode=True, sort_keys=False
            )
    except Exception:
        pass
    return raw


def _default_config_yaml() -> str:
    return """# LGPD Audit configuration
targets: []
file_scan:
  extensions: [.txt, .csv, .pdf, .docx, .xlsx]
  recursive: true
  scan_sqlite_as_db: true
  sample_limit: 5
report:
  output_dir: .
api:
  port: 8088
sqlite_path: audit_results.db
scan:
  max_workers: 1
"""


def _save_config_yaml(yaml_content: str) -> None:
    """Validate and save config file; reset in-memory config and engine so next request reloads."""
    from config.loader import normalize_config
    from core.licensing.guard import reset_license_guard_for_tests

    p = Path(_config_path)
    try:
        data = yaml.safe_load(yaml_content)
        if not isinstance(data, dict):
            raise ValueError("Config must be a YAML object")
        normalize_config(data)
    except Exception as e:
        raise ValueError(f"Invalid YAML or config: {e}") from e
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(yaml_content, encoding="utf-8")
    global _config, _audit_engine
    _config = None
    _audit_engine = None
    reset_license_guard_for_tests()


def _merge_and_save_config_yaml(submitted_yaml: str) -> None:
    """Merge submitted YAML with current config so redacted/placeholder secret values do not overwrite real secrets, then save."""
    from config.redact_config import merge_config_on_save

    current_raw = _get_config_raw()
    try:
        current_data = yaml.safe_load(current_raw)
    except Exception:
        current_data = {}
    if not isinstance(current_data, dict):
        current_data = {}
    try:
        submitted_data = yaml.safe_load(submitted_yaml)
    except Exception as e:
        raise ValueError(f"Invalid YAML: {e}") from e
    if not isinstance(submitted_data, dict):
        raise ValueError("Config must be a YAML object")
    merged = merge_config_on_save(submitted_data, current_data)
    merged_yaml = yaml.dump(
        merged, default_flow_style=False, allow_unicode=True, sort_keys=False
    )
    _save_config_yaml(merged_yaml)


def _get_config():
    global _config
    if _config is None:
        from config.loader import load_config

        if Path(_config_path).exists():
            _config = load_config(_config_path)
        else:
            _config = {
                "targets": [],
                "sqlite_path": "audit_results.db",
                "report": {"output_dir": "."},
                "api": {"port": 8088},
            }
    return _config


def _get_engine():
    global _audit_engine
    if _audit_engine is None:
        from core.engine import AuditEngine
        from core.licensing.guard import get_license_guard

        cfg = _get_config()
        _audit_engine = AuditEngine(cfg)
        get_license_guard(cfg)
    return _audit_engine


def _license_public_dict() -> dict:
    """License status for API/UI (open mode shows OPEN)."""
    try:
        from core.licensing.guard import get_license_guard

        return get_license_guard(_get_config()).context.to_public_dict()
    except Exception:
        return {"license_state": "UNKNOWN", "license_mode": "open"}


def _raise_if_license_blocks_scan() -> None:
    """403 when enforcement blocks ingest/digest."""
    from core.licensing.guard import get_license_guard

    g = get_license_guard(_get_config())
    if g.allows_scan():
        return
    c = g.context
    raise HTTPException(
        status_code=403,
        detail={
            "error": "license_blocked",
            "license_state": c.state,
            "message": "Scan blocked by licensing policy. See /health and /about for status.",
            "detail": c.detail,
        },
    )


@asynccontextmanager
async def _lifespan(app: FastAPI):
    """Load config and create AuditEngine on startup (replaces deprecated on_event)."""
    _get_config()
    _get_engine()
    yield
    # shutdown: nothing to tear down


app = FastAPI(
    title="LGPD/GDPR/CCPA Audit API",
    version=get_about_info()["version"],
    lifespan=_lifespan,
)


def _list_sessions_cached() -> list[dict]:
    """Return list of sessions; use short-TTL in-memory cache when no scan is running to reduce DB reads."""
    global _sessions_cache, _sessions_cache_time
    engine = _get_engine()
    if engine.is_running:
        _sessions_cache = None
        return engine.db_manager.list_sessions()
    now = time.monotonic()
    if (
        _sessions_cache is not None
        and (now - _sessions_cache_time) < _SESSIONS_CACHE_TTL
    ):
        return _sessions_cache
    _sessions_cache = engine.db_manager.list_sessions()
    _sessions_cache_time = now
    return _sessions_cache


def _invalidate_sessions_cache() -> None:
    """Clear sessions cache so next read gets fresh data (e.g. after scan start or session PATCH)."""
    global _sessions_cache
    _sessions_cache = None


def _raise_if_concurrent_limit_exceeded(dbm, max_concurrent: int, source: str) -> None:
    """Raise HTTPException(429) when running sessions count >= max_concurrent."""
    running = dbm.get_running_sessions_count()
    if running < max_concurrent:
        return
    raise HTTPException(
        status_code=429,
        detail={
            "error": "rate_limited",
            "reason": "Too many scans running at the same time. Wait for existing scans to finish before starting a new one.",
            "max_concurrent_scans": max_concurrent,
            "running_scans": running,
            "source": source,
        },
    )


def _raise_if_interval_limit_exceeded(
    dbm, min_interval: int, grace: int, source: str
) -> None:
    """Raise HTTPException(429) when last scan started too recently (min_interval or grace)."""
    if min_interval <= 0:
        return
    last = dbm.get_last_session()
    if not last or not last.get("started_at"):
        return
    started_at = last["started_at"]
    if started_at.tzinfo is None:
        started_at = started_at.replace(tzinfo=timezone.utc)
    now = datetime.now(timezone.utc)
    if started_at > now:
        return
    delta = (now - started_at).total_seconds()
    effective_min = float(min_interval)
    if grace > 0 and float(grace) > effective_min:
        effective_min = float(grace)
    if delta >= effective_min:
        return
    retry_after = max(0, int(effective_min - delta))
    raise HTTPException(
        status_code=429,
        detail={
            "error": "rate_limited",
            "reason": "Scans are being started too frequently. Wait before starting another scan.",
            "min_interval_seconds": int(effective_min),
            "seconds_since_last_scan": int(delta),
            "retry_after_seconds": retry_after,
            "source": source,
        },
    )


def _check_rate_limit(source: str) -> None:
    """
    Enforce basic rate limiting for scan-triggering endpoints.
    Uses normalized config (rate_limit block) plus session metadata from SQLite.
    Raises HTTPException(429) when limits are exceeded.
    """
    cfg = _get_config()
    rl = cfg.get("rate_limit") or {}
    if not rl.get("enabled"):
        return
    engine = _get_engine()
    dbm = engine.db_manager
    max_concurrent = int(rl.get("max_concurrent_scans", 1))
    min_interval = int(rl.get("min_interval_seconds", 0))
    grace = int(rl.get("grace_for_running_status", 0))
    _raise_if_concurrent_limit_exceeded(dbm, max_concurrent, source)
    _raise_if_interval_limit_exceeded(dbm, min_interval, grace, source)


# Max request body size (1 MB) for JSON/config and scan start body to reduce DoS via huge payloads
MAX_REQUEST_BODY_BYTES = 1_000_000


def _is_secure_request(request: Request) -> bool:
    """True if request was made over HTTPS (direct or via trusted proxy X-Forwarded-Proto)."""
    proto = request.headers.get("x-forwarded-proto", "").strip().lower()
    if proto == "https":
        return True
    return request.url.scheme == "https"


@app.middleware("http")
async def security_headers_middleware(request: Request, call_next):
    """
    Add current best-practice security headers to all responses.
    HSTS is set only when the request is over HTTPS to avoid locking out HTTP users.
    CSP allows 'self' and the Chart.js CDN for scripts, plus 'unsafe-inline' for existing inline styles.
    """
    response = await call_next(request)
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "DENY")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    response.headers.setdefault(
        "Permissions-Policy",
        "camera=(), microphone=(), geolocation=(), interest-cohort=(), payment=(), usb=(), "
        "magnetometer=(), gyroscope=(), accelerometer=()",
    )
    # CSP: allow self and Chart.js CDN for scripts; allow inline styles used by templates.
    response.headers.setdefault(
        "Content-Security-Policy",
        "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data:; font-src 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; "
        "base-uri 'self'; object-src 'none'",
    )
    if _is_secure_request(request):
        response.headers.setdefault(
            "Strict-Transport-Security",
            "max-age=31536000; includeSubDomains; preload",
        )
    return response


@app.middleware("http")
async def cache_control_middleware(request: Request, call_next):
    """Set Cache-Control: long-lived for static assets, no-store for API and HTML."""
    response = await call_next(request)
    if request.url.path.startswith("/static/"):
        response.headers.setdefault("Cache-Control", "public, max-age=86400")
    else:
        response.headers.setdefault("Cache-Control", "no-store")
    return response


@app.middleware("http")
async def optional_api_key_middleware(request: Request, call_next):
    """
    When ``api.require_api_key`` is true and a key is available (literal or resolved from
    ``api_key_from_env`` at config load), require **X-API-Key** or **Authorization: Bearer**
    for every path except **GET /health** (liveness: must stay unauthenticated).

    Responses: **401** if the key is missing or wrong; **503** if the operator enabled
    ``require_api_key`` but no key could be resolved (misconfiguration).
    """
    if request.url.path == "/health":
        return await call_next(request)
    cfg = _get_config()
    api_cfg = cfg.get("api") or {}
    if not api_cfg.get("require_api_key"):
        return await call_next(request)
    if not effective_api_key_configured(api_cfg):
        return JSONResponse(
            status_code=503,
            content={
                "detail": (
                    "api.require_api_key is true but no API key is configured. "
                    "Set api.api_key or api.api_key_from_env (with the env var at process start). "
                    "See docs/ops/API_KEY_FROM_ENV_OPERATOR_STEPS.md."
                )
            },
        )
    expected = api_cfg.get("api_key") or ""
    provided = (request.headers.get("x-api-key") or "").strip()
    if not provided and request.headers.get("authorization"):
        auth = request.headers.get("authorization", "").strip()
        if auth.lower().startswith("bearer "):
            provided = auth[7:].strip()
    if not provided or provided != expected:
        return JSONResponse(
            status_code=401, content={"detail": "Missing or invalid API key"}
        )
    return await call_next(request)


@app.middleware("http")
async def request_body_size_middleware(request: Request, call_next):
    """
    Reject requests with Content-Length exceeding MAX_REQUEST_BODY_BYTES (1 MB) to prevent
    DoS via huge JSON or form bodies (e.g. POST /config, POST /scan, POST /scan_database).
    Added last so it runs first (outermost) in the middleware stack.
    """
    content_length = request.headers.get("content-length")
    if content_length is not None:
        try:
            if int(content_length) > MAX_REQUEST_BODY_BYTES:
                return JSONResponse(
                    status_code=413,
                    content={"detail": "Request body too large. Maximum size is 1 MB."},
                )
        except ValueError:
            pass  # Invalid Content-Length; let the server handle it
    return await call_next(request)


app.mount("/static", StaticFiles(directory=str(_api_dir / "static")), name="static")


@app.get("/health")
async def health():
    """
    Liveness/readiness probe for Docker, Swarm and Kubernetes.

    Semantics: **always unauthenticated** (no API key). Returns minimal JSON for
    orchestrators; see SECURITY.md / USAGE.md for difference vs protected routes.
    """
    body: dict = {"status": "ok"}
    body["license"] = _license_public_dict()
    body["dashboard_transport"] = get_dashboard_transport_snapshot()
    return body


@app.get("/help", response_class=HTMLResponse)
async def help_page(request: Request):
    """Help and documentation page: quickstart, config example, links to README/USAGE docs."""
    return templates.TemplateResponse(
        request=request,
        name="help.html",
        context=_template_context({}),
    )


@app.get("/about", response_class=HTMLResponse)
async def about_page(request: Request):
    """About: application name, version, author and license (same as established in the project LICENSE)."""
    return templates.TemplateResponse(
        request=request,
        name="about.html",
        context=_template_context(
            {"about": _about_info(), "license": _license_public_dict()}
        ),
    )


@app.get("/about/json")
async def about_json():
    """Machine-readable about info (name, version, author, license) for API consumers."""
    info = _about_info()
    info["license"] = _license_public_dict()
    return info


def _build_chart_data(sessions: list[dict]) -> list[dict]:
    """
    Build progress chart data: one point per session (oldest first) with total findings and risk score.
    Score formula: min(100, total_findings * 2 + scan_failures * 5). Used for dashboard "Progress over time" chart.
    """
    ordered = list(reversed(sessions))  # chronological order for time axis
    out = []
    for s in ordered:
        total = s["database_findings"] + s["filesystem_findings"]
        score = min(100, total * 2 + s["scan_failures"] * 5)
        started = s.get("started_at") or ""
        # Short label for axis (date only if ISO format)
        label = started[:10] if len(started) >= 10 else started or "—"
        out.append(
            {
                "label": label,
                "started_at": started,
                "total_findings": total,
                "score": round(score, 1),
            }
        )
    return out


@app.get("/", response_class=HTMLResponse)
async def dashboard(request: Request):
    """Dashboard: scan status, discovery stats, progress chart, recent sessions, start scan."""
    engine = _get_engine()
    status = {
        "running": engine.is_running,
        "current_session_id": engine.db_manager.current_session_id,
        "findings_count": engine.get_current_findings_count(),
    }
    sessions = _list_sessions_cached()
    last_session = sessions[0] if sessions else None
    chart_data = _build_chart_data(sessions)
    return templates.TemplateResponse(
        request=request,
        name="dashboard.html",
        context=_template_context(
            {
                "status": status,
                "sessions": sessions,
                "last_session": last_session,
                "chart_data": chart_data,
                "about": _about_info(),
                "license": _license_public_dict(),
            }
        ),
    )


@app.get("/config", response_class=HTMLResponse)
async def config_page(request: Request):
    """Configuration editor (YAML). Secret values are redacted so the UI never displays them. Query: saved=1 or error=... for feedback after POST."""
    saved = request.query_params.get("saved") == "1"
    error = request.query_params.get("error")
    return templates.TemplateResponse(
        request=request,
        name=_TEMPLATE_CONFIG,
        context=_template_context(
            {
                "config_path": _get_config_path(),
                "config_yaml": _get_config_yaml_for_display(),
                "config_saved": saved,
                "config_save_error": error,
            }
        ),
    )


@app.post("/config", response_class=HTMLResponse)
async def config_save(request: Request):
    """Save configuration (form body: yaml=...). Redacted/placeholder secrets are merged with current so they are not overwritten. Redirects back to GET /config with success or error."""
    form = await request.form()
    yaml_content = form.get("yaml", "")
    if not yaml_content:
        return templates.TemplateResponse(
            request=request,
            name=_TEMPLATE_CONFIG,
            context=_template_context(
                {
                    "config_path": _get_config_path(),
                    "config_yaml": _get_config_yaml_for_display(),
                    "config_saved": False,
                    "config_save_error": "No YAML content provided.",
                }
            ),
        )
    try:
        _merge_and_save_config_yaml(yaml_content)
        return RedirectResponse(url="/config?saved=1", status_code=303)
    except ValueError as e:
        return templates.TemplateResponse(
            request=request,
            name=_TEMPLATE_CONFIG,
            context=_template_context(
                {
                    "config_path": _get_config_path(),
                    "config_yaml": yaml_content,
                    "config_saved": False,
                    "config_save_error": str(e),
                }
            ),
        )


@app.get("/reports", response_class=HTMLResponse)
async def reports_page(request: Request):
    """Reports list page with download links. Query: sort=date_desc (newest first, default) or sort=date_asc (oldest first)."""
    sessions = _list_sessions_cached()
    sort = (request.query_params.get("sort") or "date_desc").strip().lower()
    if sort == "date_asc":
        sessions = list(reversed(sessions))
        sort = "date_asc"
    else:
        sort = "date_desc"
    return templates.TemplateResponse(
        request=request,
        name="reports.html",
        context=_template_context(
            {"sessions": sessions, "sort": sort, "about": _about_info()}
        ),
    )


_RATE_LIMIT_429 = {
    429: {
        "description": "Rate limit exceeded (too many concurrent scans or scans started too frequently)."
    }
}
_NOT_FOUND_404 = {404: {"description": "Resource not found."}}
_SESSION_RESPONSES = {
    400: {"description": "Invalid session_id (empty or invalid format)."},
    404: {"description": "Session or resource not found."},
}


@app.post("/scan", responses=_RATE_LIMIT_429)
@app.post("/start", responses=_RATE_LIMIT_429)
async def start_scan(
    background_tasks: BackgroundTasks, body: ScanStartBody | None = None
):
    """Start audit in background. Optional body: tenant, technician, scan_compressed, content_type_check. Returns session_id."""
    _raise_if_license_blocks_scan()
    engine = _get_engine()
    if engine.is_running:
        raise HTTPException(status_code=409, detail="Audit already in progress.")
    # Global rate limiting (DB-backed) to avoid accidental DoS from repeated scans
    _check_rate_limit(source="scan")
    from core.session import new_session_id
    from core.validation import sanitize_tenant_technician

    session_id = new_session_id()
    tenant = sanitize_tenant_technician((body.tenant if body else None) or None)
    technician = sanitize_tenant_technician((body.technician if body else None) or None)
    engine.db_manager.set_current_session_id(session_id)
    engine.db_manager.create_session_record(
        session_id,
        tenant_name=tenant,
        technician_name=technician,
    )

    # Run-local overrides: merge into file_scan for this run only; restore after (same pattern as scan_compressed).
    fs = engine.config.get("file_scan") or {}
    prev_scan_compressed = fs.get("scan_compressed")
    prev_use_content_type = fs.get("use_content_type")

    if body and getattr(body, "scan_compressed", None) is True:
        engine.config.setdefault("file_scan", {})["scan_compressed"] = True
    if body and getattr(body, "content_type_check", None) is True:
        engine.config.setdefault("file_scan", {})["use_content_type"] = True

    def run_targets():
        try:
            engine._run_audit_targets()
        finally:
            if "file_scan" in engine.config:
                if prev_scan_compressed is None:
                    engine.config["file_scan"].pop("scan_compressed", None)
                else:
                    engine.config["file_scan"]["scan_compressed"] = prev_scan_compressed
                if prev_use_content_type is None:
                    engine.config["file_scan"].pop("use_content_type", None)
                else:
                    engine.config["file_scan"]["use_content_type"] = (
                        prev_use_content_type
                    )
        from utils.notify import notify_scan_complete_background

        notify_scan_complete_background(engine.config, engine.db_manager, session_id)

    background_tasks.add_task(run_targets)
    _invalidate_sessions_cache()
    return {"status": "started", "session_id": session_id}


@app.get("/status")
async def get_status():
    """Return running, current_session_id, findings_count."""
    engine = _get_engine()
    runtime_trust = get_runtime_trust_snapshot(_get_config())
    return {
        "running": engine.is_running,
        "current_session_id": engine.db_manager.current_session_id,
        "findings_count": engine.get_current_findings_count(),
        "runtime_trust": runtime_trust,
        "dashboard_transport": get_dashboard_transport_snapshot(),
    }


@app.get("/report", responses=_NOT_FOUND_404)
async def download_report():
    """Download last generated report file (Excel)."""
    engine = _get_engine()
    path = engine.get_last_report_path()
    safe_path = _safe_report_output_path(path, engine) if path else None
    if not safe_path:
        # Try to generate from last session (avoid Path(raw_user_path) for CodeQL path-injection).
        sid = engine.db_manager.current_session_id
        if sid:
            path = engine.generate_final_reports(sid)
        else:
            sessions = engine.db_manager.list_sessions()
            if sessions:
                path = engine.generate_final_reports(sessions[0]["session_id"])
            else:
                path = None
        safe_path = _safe_report_output_path(path, engine) if path else None
    if safe_path:
        return FileResponse(
            safe_path,
            filename=safe_path.name,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
    raise HTTPException(
        status_code=404, detail="Report not available. Run a scan first."
    )


@app.get("/heatmap", responses=_NOT_FOUND_404)
async def download_heatmap():
    """Download last generated heatmap PNG (sensitivity/risk heatmap for the most recent session)."""
    engine = _get_engine()
    resolved = _safe_report_path_for_heatmap(engine)
    if not resolved:
        raise HTTPException(
            status_code=404, detail="Heatmap not available. Run a scan first."
        )
    _, sid = resolved
    heatmap_resp = _heatmap_png_response(engine, sid)
    if heatmap_resp:
        return heatmap_resp
    raise HTTPException(
        status_code=404,
        detail="Heatmap not available. Run a scan first or ensure the report was generated.",
    )


@app.get("/list")
async def list_sessions_api(sort: str = "date_desc"):
    """List past scan sessions (session_id, timestamp, tenant_name, counts) for report recreation (JSON API). Query: sort=date_desc (newest first, default) or sort=date_asc (oldest first)."""
    sessions = _list_sessions_cached()
    if (sort or "").strip().lower() == "date_asc":
        sessions = list(reversed(sessions))
    return {"sessions": sessions}


class SessionTenantUpdate(BaseModel):
    """Body for PATCH /sessions/{session_id}: set tenant/customer name for a session."""

    tenant: str | None = None


class SessionTechnicianUpdate(BaseModel):
    """Body for PATCH /sessions/{session_id}/technician: set technician/operator name for a session."""

    technician: str | None = None


@app.patch("/sessions/{session_id}", responses=_SESSION_RESPONSES)
async def update_session_tenant(session_id: str, body: SessionTenantUpdate):
    """Set or clear the tenant/customer name for an existing scan session."""
    _validate_session_id(session_id)
    engine = _get_engine()
    sessions = [
        s
        for s in engine.db_manager.list_sessions()
        if s.get("session_id") == session_id
    ]
    if not sessions:
        raise HTTPException(status_code=404, detail=f"Session {session_id} not found.")
    from core.validation import sanitize_tenant_technician

    tenant = sanitize_tenant_technician(body.tenant)
    engine.db_manager.update_session_tenant(session_id, tenant)
    _invalidate_sessions_cache()
    return {"session_id": session_id, "tenant": tenant}


@app.patch("/sessions/{session_id}/technician", responses=_SESSION_RESPONSES)
async def update_session_technician(session_id: str, body: SessionTechnicianUpdate):
    """Set or clear the technician/operator name for an existing scan session."""
    _validate_session_id(session_id)
    engine = _get_engine()
    sessions = [
        s
        for s in engine.db_manager.list_sessions()
        if s.get("session_id") == session_id
    ]
    if not sessions:
        raise HTTPException(status_code=404, detail=f"Session {session_id} not found.")
    from core.validation import sanitize_tenant_technician

    technician = sanitize_tenant_technician(body.technician)
    engine.db_manager.update_session_technician(session_id, technician)
    _invalidate_sessions_cache()
    return {"session_id": session_id, "technician": technician}


@app.get("/reports/{session_id}", responses=_SESSION_RESPONSES)
async def download_report_by_session(session_id: str):
    """Regenerate and download Excel report for the given session_id."""
    _validate_session_id(session_id)
    engine = _get_engine()
    path = engine.generate_final_reports(session_id)
    if path:
        candidate = _safe_report_output_path(path, engine)
        if candidate is None:
            # Path is outside configured report directory or does not exist.
            raise HTTPException(
                status_code=403,
                detail="Report path is outside the configured report directory.",
            )
        return FileResponse(
            candidate,
            filename=candidate.name,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
    raise HTTPException(
        status_code=404,
        detail=f"No data for session {session_id} or report generation failed.",
    )


@app.get("/heatmap/{session_id}", responses=_SESSION_RESPONSES)
async def download_heatmap_by_session(session_id: str):
    """Regenerate report (if needed) and download heatmap PNG for the given session_id."""
    _validate_session_id(session_id)
    engine = _get_engine()
    path = engine.generate_final_reports(session_id)
    if not path or _safe_report_output_path(path, engine) is None:
        raise HTTPException(
            status_code=404,
            detail=f"No data for session {session_id} or report generation failed.",
        )
    # Heatmap file is resolved under config output_dir only; body response avoids FileResponse path sink.
    heatmap_resp = _heatmap_png_response(engine, session_id)
    if heatmap_resp:
        return heatmap_resp
    raise HTTPException(
        status_code=404,
        detail=f"Heatmap not available for session {session_id}. Run a scan and ensure findings exist.",
    )


@app.get("/logs", responses=_NOT_FOUND_404)
async def download_latest_log():
    """
    Download the most recent audit_YYYYMMDD.log file from the current working directory.
    This file contains connection and finding logs for recent scan sessions.
    """
    log_dir = Path(".")
    candidates = sorted(
        log_dir.glob("audit_*.log"), key=lambda p: p.stat().st_mtime, reverse=True
    )
    if not candidates:
        raise HTTPException(status_code=404, detail="No log files found.")
    latest = candidates[0]
    return FileResponse(latest, filename=latest.name, media_type="text/plain")


@app.get("/logs/{session_id}", responses=_SESSION_RESPONSES)
async def download_log_for_session(session_id: str):
    """
    Download the first audit_YYYYMMDD.log file that contains the given session_id.
    This allows linking scan sessions to their corresponding console/audit trace.
    Paths used are only from glob("audit_*.log"); session_id is not used in path expressions.
    """
    _validate_session_id(session_id)
    log_dir = Path(".")
    candidates = sorted(
        log_dir.glob("audit_*.log"), key=lambda p: p.stat().st_mtime, reverse=True
    )
    if not candidates:
        raise HTTPException(status_code=404, detail="No log files found.")
    for p in candidates:
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if session_id in text:
            return FileResponse(p, filename=p.name, media_type="text/plain")
    raise HTTPException(
        status_code=404, detail=f"No log file contains session_id {session_id}."
    )


@app.post("/scan_database", responses=_RATE_LIMIT_429)
async def scan_database(config: DatabaseConfig, background_tasks: BackgroundTasks):
    """One-off scan of a single database (body: name, host, port, user, password, database, optional driver). Starts in background; returns session_id."""
    _raise_if_license_blocks_scan()
    engine = _get_engine()
    if engine.is_running:
        raise HTTPException(status_code=409, detail="Audit already in progress.")
    # Apply same rate limiting as for full scans
    _check_rate_limit(source="scan_database")
    target = {
        "name": config.name,
        "type": "database",
        "driver": config.driver,
        "host": config.host,
        "port": config.port,
        "user": config.user,
        "pass": config.password,
        "database": config.database,
    }
    from core.session import new_session_id
    from core.validation import sanitize_tenant_technician

    session_id = new_session_id()
    tenant = sanitize_tenant_technician(config.tenant)
    technician = sanitize_tenant_technician(config.technician)
    engine.db_manager.set_current_session_id(session_id)
    engine.db_manager.create_session_record(
        session_id,
        tenant_name=tenant,
        technician_name=technician,
    )

    def run_one_target():
        engine._is_running = True
        try:
            engine._run_target(target)
        finally:
            engine._is_running = False
            engine.db_manager.finish_session(session_id, "completed")
        from utils.notify import notify_scan_complete_background

        notify_scan_complete_background(engine.config, engine.db_manager, session_id)

    background_tasks.add_task(run_one_target)
    _invalidate_sessions_cache()
    return {"status": "started", "session_id": session_id}
