"""
FastAPI app: dashboard (GET /), config (GET/POST /config), reports list (GET /reports).
API: POST /scan and /start (optional tenant/technician tags), GET /status, /report, /list,
GET /reports/{session_id}, POST /scan_database (optional tenant/technician), PATCH /sessions/{session_id}
and /sessions/{session_id}/technician for metadata updates. On startup load config (config.yaml or CONFIG_PATH)
and create a singleton AuditEngine.

Path safety: all path expressions use only validated session_id or server-controlled paths;
user-supplied session_id is validated to prevent path traversal before use in file paths.

Cache: static assets get long-lived Cache-Control; API/HTML get no-store. Sessions list is cached
in-memory for a short TTL when no scan is running to reduce SQLite reads on repeated dashboard loads.

Security: default middleware adds X-Content-Type-Options, X-Frame-Options, Content-Security-Policy,
Referrer-Policy, Permissions-Policy, and Strict-Transport-Security (only when served over HTTPS).
"""
import os
import re
import time
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path

import yaml
from fastapi import BackgroundTasks, FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel

from core.about import get_about_info


def _about_info() -> dict:
    """Application name, version, author and license (from core.about, matches LICENSE and README)."""
    return get_about_info()


# In-memory cache for list_sessions (TTL seconds). Bypassed when a scan is running.
_SESSIONS_CACHE_TTL = 2.0
_sessions_cache: list[dict] | None = None
_sessions_cache_time: float = 0.0

_api_dir = Path(__file__).resolve().parent
templates = Jinja2Templates(directory=str(_api_dir / "templates"))

# Template names (avoid duplicating string literals).
_TEMPLATE_CONFIG = "config.html"

# Session IDs are generated by core.session (e.g. 12 hex + _ + timestamp). Used in path segments.
_SESSION_ID_PATTERN = re.compile(r"^\w{12,64}$", re.ASCII)


def _validate_session_id(session_id: str) -> None:
    """Reject session_id that could be used in path traversal. Raises HTTPException if invalid."""
    if not session_id or not isinstance(session_id, str):
        raise HTTPException(status_code=400, detail="Invalid session_id.")
    if not _SESSION_ID_PATTERN.fullmatch(session_id.strip()):
        raise HTTPException(
            status_code=400,
            detail="Invalid session_id: only alphanumeric and underscore, 12–64 characters.",
        )


class DatabaseConfig(BaseModel):
    """Single database target for one-off scan via POST /scan_database."""
    name: str
    host: str
    port: int
    user: str
    password: str
    database: str
    driver: str = "postgresql+psycopg2"
    tenant: str | None = None  # optional customer/tenant name for this scan
    technician: str | None = None  # optional technician/operator name for this scan


class ScanStartBody(BaseModel):
    """Optional body for POST /scan to associate the scan with a tenant/customer and technician/operator."""
    tenant: str | None = None
    technician: str | None = None

# Load config and create engine at import time (or on startup event)
_config_path = os.environ.get("CONFIG_PATH", "config.yaml")
if not Path(_config_path).exists():
    _config_path = "config.yaml"
_config = None
_audit_engine = None


def _get_config_path() -> str:
    """Return path to config file (for dashboard display and save)."""
    return _config_path


def _get_config_raw() -> str:
    """Return raw config file content (YAML) for editing. If file missing, return default YAML."""
    p = Path(_config_path)
    if p.exists():
        return p.read_text(encoding="utf-8")
    return _default_config_yaml()


def _default_config_yaml() -> str:
    return """# LGPD Audit configuration
targets: []
file_scan:
  extensions: [.txt, .csv, .pdf, .docx, .xlsx]
  recursive: true
  scan_sqlite_as_db: true
  sample_limit: 5
report:
  output_dir: .
api:
  port: 8088
sqlite_path: audit_results.db
scan:
  max_workers: 1
"""


def _save_config_yaml(yaml_content: str) -> None:
    """Validate and save config file; reset in-memory config and engine so next request reloads."""
    from config.loader import normalize_config
    p = Path(_config_path)
    try:
        data = yaml.safe_load(yaml_content)
        if not isinstance(data, dict):
            raise ValueError("Config must be a YAML object")
        normalize_config(data)
    except Exception as e:
        raise ValueError(f"Invalid YAML or config: {e}") from e
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(yaml_content, encoding="utf-8")
    global _config, _audit_engine
    _config = None
    _audit_engine = None


def _get_config():
    global _config
    if _config is None:
        from config.loader import load_config
        if Path(_config_path).exists():
            _config = load_config(_config_path)
        else:
            _config = {"targets": [], "sqlite_path": "audit_results.db", "report": {"output_dir": "."}, "api": {"port": 8088}}
    return _config


def _get_engine():
    global _audit_engine
    if _audit_engine is None:
        from core.engine import AuditEngine
        _audit_engine = AuditEngine(_get_config())
    return _audit_engine


@asynccontextmanager
async def _lifespan(app: FastAPI):
    """Load config and create AuditEngine on startup (replaces deprecated on_event)."""
    _get_config()
    _get_engine()
    yield
    # shutdown: nothing to tear down


app = FastAPI(
    title="LGPD/GDPR/CCPA Audit API",
    version=get_about_info()["version"],
    lifespan=_lifespan,
)


def _list_sessions_cached() -> list[dict]:
    """Return list of sessions; use short-TTL in-memory cache when no scan is running to reduce DB reads."""
    global _sessions_cache, _sessions_cache_time
    engine = _get_engine()
    if engine.is_running:
        _sessions_cache = None
        return engine.db_manager.list_sessions()
    now = time.monotonic()
    if _sessions_cache is not None and (now - _sessions_cache_time) < _SESSIONS_CACHE_TTL:
        return _sessions_cache
    _sessions_cache = engine.db_manager.list_sessions()
    _sessions_cache_time = now
    return _sessions_cache


def _invalidate_sessions_cache() -> None:
    """Clear sessions cache so next read gets fresh data (e.g. after scan start or session PATCH)."""
    global _sessions_cache
    _sessions_cache = None


def _raise_if_concurrent_limit_exceeded(dbm, max_concurrent: int, source: str) -> None:
    """Raise HTTPException(429) when running sessions count >= max_concurrent."""
    running = dbm.get_running_sessions_count()
    if running < max_concurrent:
        return
    raise HTTPException(
        status_code=429,
        detail={
            "error": "rate_limited",
            "reason": "Too many scans running at the same time. Wait for existing scans to finish before starting a new one.",
            "max_concurrent_scans": max_concurrent,
            "running_scans": running,
            "source": source,
        },
    )


def _raise_if_interval_limit_exceeded(dbm, min_interval: int, grace: int, source: str) -> None:
    """Raise HTTPException(429) when last scan started too recently (min_interval or grace)."""
    if min_interval <= 0:
        return
    last = dbm.get_last_session()
    if not last or not last.get("started_at"):
        return
    started_at = last["started_at"]
    if started_at.tzinfo is None:
        started_at = started_at.replace(tzinfo=timezone.utc)
    now = datetime.now(timezone.utc)
    if started_at > now:
        return
    delta = (now - started_at).total_seconds()
    effective_min = float(min_interval)
    if grace > 0 and float(grace) > effective_min:
        effective_min = float(grace)
    if delta >= effective_min:
        return
    retry_after = max(0, int(effective_min - delta))
    raise HTTPException(
        status_code=429,
        detail={
            "error": "rate_limited",
            "reason": "Scans are being started too frequently. Wait before starting another scan.",
            "min_interval_seconds": int(effective_min),
            "seconds_since_last_scan": int(delta),
            "retry_after_seconds": retry_after,
            "source": source,
        },
    )


def _check_rate_limit(source: str) -> None:
    """
    Enforce basic rate limiting for scan-triggering endpoints.
    Uses normalized config (rate_limit block) plus session metadata from SQLite.
    Raises HTTPException(429) when limits are exceeded.
    """
    cfg = _get_config()
    rl = (cfg.get("rate_limit") or {})
    if not rl.get("enabled"):
        return
    engine = _get_engine()
    dbm = engine.db_manager
    max_concurrent = int(rl.get("max_concurrent_scans", 1))
    min_interval = int(rl.get("min_interval_seconds", 0))
    grace = int(rl.get("grace_for_running_status", 0))
    _raise_if_concurrent_limit_exceeded(dbm, max_concurrent, source)
    _raise_if_interval_limit_exceeded(dbm, min_interval, grace, source)


# Max request body size (1 MB) for JSON/config and scan start body to reduce DoS via huge payloads
MAX_REQUEST_BODY_BYTES = 1_000_000


def _is_secure_request(request: Request) -> bool:
    """True if request was made over HTTPS (direct or via trusted proxy X-Forwarded-Proto)."""
    proto = request.headers.get("x-forwarded-proto", "").strip().lower()
    if proto == "https":
        return True
    return request.url.scheme == "https"


@app.middleware("http")
async def security_headers_middleware(request: Request, call_next):
    """
    Add current best-practice security headers to all responses.
    HSTS is set only when the request is over HTTPS to avoid locking out HTTP users.
    CSP allows 'self' and the Chart.js CDN for scripts, plus 'unsafe-inline' for existing inline styles.
    """
    response = await call_next(request)
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "DENY")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    response.headers.setdefault(
        "Permissions-Policy",
        "camera=(), microphone=(), geolocation=(), interest-cohort=(), payment=(), usb=(), "
        "magnetometer=(), gyroscope=(), accelerometer=()",
    )
    # CSP: allow self and Chart.js CDN for scripts; allow inline styles used by templates.
    response.headers.setdefault(
        "Content-Security-Policy",
        "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data:; font-src 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; "
        "base-uri 'self'; object-src 'none'",
    )
    if _is_secure_request(request):
        response.headers.setdefault(
            "Strict-Transport-Security",
            "max-age=31536000; includeSubDomains; preload",
        )
    return response


@app.middleware("http")
async def cache_control_middleware(request: Request, call_next):
    """Set Cache-Control: long-lived for static assets, no-store for API and HTML."""
    response = await call_next(request)
    if request.url.path.startswith("/static/"):
        response.headers.setdefault("Cache-Control", "public, max-age=86400")
    else:
        response.headers.setdefault("Cache-Control", "no-store")
    return response


@app.middleware("http")
async def optional_api_key_middleware(request: Request, call_next):
    """
    When api.require_api_key is true and api.api_key is set, require X-API-Key or Authorization: Bearer.
    /health is always allowed (no key) so load balancers get 200. Returns 401 if key missing or wrong.
    """
    if request.url.path == "/health":
        return await call_next(request)
    cfg = _get_config()
    api_cfg = cfg.get("api") or {}
    if not api_cfg.get("require_api_key") or not api_cfg.get("api_key"):
        return await call_next(request)
    expected = api_cfg.get("api_key") or ""
    provided = (request.headers.get("x-api-key") or "").strip()
    if not provided and request.headers.get("authorization"):
        auth = request.headers.get("authorization", "").strip()
        if auth.lower().startswith("bearer "):
            provided = auth[7:].strip()
    if not provided or provided != expected:
        return JSONResponse(status_code=401, content={"detail": "Missing or invalid API key"})
    return await call_next(request)


@app.middleware("http")
async def request_body_size_middleware(request: Request, call_next):
    """
    Reject requests with Content-Length exceeding MAX_REQUEST_BODY_BYTES (1 MB) to prevent
    DoS via huge JSON or form bodies (e.g. POST /config, POST /scan, POST /scan_database).
    Added last so it runs first (outermost) in the middleware stack.
    """
    content_length = request.headers.get("content-length")
    if content_length is not None:
        try:
            if int(content_length) > MAX_REQUEST_BODY_BYTES:
                return JSONResponse(
                    status_code=413,
                    content={"detail": "Request body too large. Maximum size is 1 MB."},
                )
        except ValueError:
            pass  # Invalid Content-Length; let the server handle it
    return await call_next(request)


app.mount("/static", StaticFiles(directory=str(_api_dir / "static")), name="static")


@app.get("/health")
async def health():
    """Liveness/readiness probe for Docker, Swarm and Kubernetes."""
    return {"status": "ok"}


@app.get("/help", response_class=HTMLResponse)
async def help_page(request: Request):
    """Help and documentation page: quickstart, config example, links to README/USAGE docs."""
    return templates.TemplateResponse(
        request=request,
        name="help.html",
        context={},
    )


@app.get("/about", response_class=HTMLResponse)
async def about_page(request: Request):
    """About: application name, version, author and license (same as established in the project LICENSE)."""
    return templates.TemplateResponse(
        request=request,
        name="about.html",
        context={"about": _about_info()},
    )


@app.get("/about/json")
async def about_json():
    """Machine-readable about info (name, version, author, license) for API consumers."""
    return _about_info()


def _build_chart_data(sessions: list[dict]) -> list[dict]:
    """
    Build progress chart data: one point per session (oldest first) with total findings and risk score.
    Score formula: min(100, total_findings * 2 + scan_failures * 5). Used for dashboard "Progress over time" chart.
    """
    ordered = list(reversed(sessions))  # chronological order for time axis
    out = []
    for s in ordered:
        total = s["database_findings"] + s["filesystem_findings"]
        score = min(100, total * 2 + s["scan_failures"] * 5)
        started = s.get("started_at") or ""
        # Short label for axis (date only if ISO format)
        label = started[:10] if len(started) >= 10 else started or "—"
        out.append({"label": label, "started_at": started, "total_findings": total, "score": round(score, 1)})
    return out


@app.get("/", response_class=HTMLResponse)
async def dashboard(request: Request):
    """Dashboard: scan status, discovery stats, progress chart, recent sessions, start scan."""
    engine = _get_engine()
    status = {
        "running": engine.is_running,
        "current_session_id": engine.db_manager.current_session_id,
        "findings_count": engine.get_current_findings_count(),
    }
    sessions = _list_sessions_cached()
    last_session = sessions[0] if sessions else None
    chart_data = _build_chart_data(sessions)
    return templates.TemplateResponse(
        request=request,
        name="dashboard.html",
        context={
            "status": status,
            "sessions": sessions,
            "last_session": last_session,
            "chart_data": chart_data,
            "about": _about_info(),
        },
    )


@app.get("/config", response_class=HTMLResponse)
async def config_page(request: Request):
    """Configuration editor (YAML). Query: saved=1 or error=... for feedback after POST."""
    saved = request.query_params.get("saved") == "1"
    error = request.query_params.get("error")
    return templates.TemplateResponse(
        request=request,
        name=_TEMPLATE_CONFIG,
        context={
            "config_path": _get_config_path(),
            "config_yaml": _get_config_raw(),
            "config_saved": saved,
            "config_save_error": error,
        },
    )


@app.post("/config", response_class=HTMLResponse)
async def config_save(request: Request):
    """Save configuration (form body: yaml=...). Redirects back to GET /config with success or error."""
    form = await request.form()
    yaml_content = form.get("yaml", "")
    if not yaml_content:
        return templates.TemplateResponse(
            request=request,
            name=_TEMPLATE_CONFIG,
            context={
                "config_path": _get_config_path(),
                "config_yaml": _get_config_raw(),
                "config_saved": False,
                "config_save_error": "No YAML content provided.",
            },
        )
    try:
        _save_config_yaml(yaml_content)
        return RedirectResponse(url="/config?saved=1", status_code=303)
    except ValueError as e:
        return templates.TemplateResponse(
            request=request,
            name=_TEMPLATE_CONFIG,
            context={
                "config_path": _get_config_path(),
                "config_yaml": yaml_content,
                "config_saved": False,
                "config_save_error": str(e),
            },
        )


@app.get("/reports", response_class=HTMLResponse)
async def reports_page(request: Request):
    """Reports list page with download links. Query: sort=date_desc (newest first, default) or sort=date_asc (oldest first)."""
    sessions = _list_sessions_cached()
    sort = (request.query_params.get("sort") or "date_desc").strip().lower()
    if sort == "date_asc":
        sessions = list(reversed(sessions))
        sort = "date_asc"
    else:
        sort = "date_desc"
    return templates.TemplateResponse(
        request=request,
        name="reports.html",
        context={"sessions": sessions, "sort": sort, "about": _about_info()},
    )


_RATE_LIMIT_429 = {429: {"description": "Rate limit exceeded (too many concurrent scans or scans started too frequently)."}}
_NOT_FOUND_404 = {404: {"description": "Resource not found."}}
_SESSION_RESPONSES = {400: {"description": "Invalid session_id (empty or invalid format)."}, 404: {"description": "Session or resource not found."}}


@app.post("/scan", responses=_RATE_LIMIT_429)
@app.post("/start", responses=_RATE_LIMIT_429)
async def start_scan(background_tasks: BackgroundTasks, body: ScanStartBody | None = None):
    """Start audit in background. Optional body.tenant and body.technician to tag the scan. Returns session_id."""
    engine = _get_engine()
    if engine.is_running:
        raise HTTPException(status_code=409, detail="Audit already in progress.")
    # Global rate limiting (DB-backed) to avoid accidental DoS from repeated scans
    _check_rate_limit(source="scan")
    from core.session import new_session_id
    from core.validation import sanitize_tenant_technician
    session_id = new_session_id()
    tenant = sanitize_tenant_technician((body.tenant if body else None) or None)
    technician = sanitize_tenant_technician((body.technician if body else None) or None)
    engine.db_manager.set_current_session_id(session_id)
    engine.db_manager.create_session_record(
        session_id,
        tenant_name=tenant,
        technician_name=technician,
    )
    def run_targets():
        engine._run_audit_targets()
    background_tasks.add_task(run_targets)
    _invalidate_sessions_cache()
    return {"status": "started", "session_id": session_id}


@app.get("/status")
async def get_status():
    """Return running, current_session_id, findings_count."""
    engine = _get_engine()
    return {
        "running": engine.is_running,
        "current_session_id": engine.db_manager.current_session_id,
        "findings_count": engine.get_current_findings_count(),
    }


@app.get("/report", responses=_NOT_FOUND_404)
async def download_report():
    """Download last generated report file (Excel)."""
    engine = _get_engine()
    path = engine.get_last_report_path()
    if not path or not Path(path).exists():
        # Try to generate from last session
        sid = engine.db_manager.current_session_id
        if sid:
            path = engine.generate_final_reports(sid)
        else:
            sessions = engine.db_manager.list_sessions()
            if sessions:
                path = engine.generate_final_reports(sessions[0]["session_id"])
    if path and Path(path).exists():
        return FileResponse(path, filename=Path(path).name, media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    raise HTTPException(status_code=404, detail="Report not available. Run a scan first.")


@app.get("/heatmap", responses=_NOT_FOUND_404)
async def download_heatmap():
    """Download last generated heatmap PNG (sensitivity/risk heatmap for the most recent session)."""
    engine = _get_engine()
    # Try to reuse last report path; if missing, generate from last known session as in /report.
    path = engine.get_last_report_path()
    sid: str | None = None
    if not path or not Path(path).exists():
        sid = engine.db_manager.current_session_id or None
        if not sid:
            sessions = engine.db_manager.list_sessions()
            if sessions:
                sid = sessions[0]["session_id"]
        if not sid:
            raise HTTPException(status_code=404, detail="Heatmap not available. Run a scan first.")
        path = engine.generate_final_reports(sid)
    # At this point we have a report path and can infer session_id if needed
    if not path or not Path(path).exists():
        raise HTTPException(status_code=404, detail="Heatmap not available. Run a scan first.")
    report_path = Path(path)
    if not sid:
        # Recover session prefix from report filename: Relatorio_Auditoria_<session_prefix>.xlsx
        name = report_path.name
        prefix = name.removeprefix("Relatorio_Auditoria_").removesuffix(".xlsx")
        sid = prefix
    out_dir = report_path.parent
    heatmap_path = out_dir / f"heatmap_{sid[:12]}.png"
    if heatmap_path.exists():
        return FileResponse(heatmap_path, filename=heatmap_path.name, media_type="image/png")
    raise HTTPException(status_code=404, detail="Heatmap not available. Run a scan first or ensure the report was generated.")


@app.get("/list")
async def list_sessions_api(sort: str = "date_desc"):
    """List past scan sessions (session_id, timestamp, tenant_name, counts) for report recreation (JSON API). Query: sort=date_desc (newest first, default) or sort=date_asc (oldest first)."""
    sessions = _list_sessions_cached()
    if (sort or "").strip().lower() == "date_asc":
        sessions = list(reversed(sessions))
    return {"sessions": sessions}


class SessionTenantUpdate(BaseModel):
    """Body for PATCH /sessions/{session_id}: set tenant/customer name for a session."""
    tenant: str | None = None


class SessionTechnicianUpdate(BaseModel):
    """Body for PATCH /sessions/{session_id}/technician: set technician/operator name for a session."""
    technician: str | None = None


@app.patch("/sessions/{session_id}", responses=_SESSION_RESPONSES)
async def update_session_tenant(session_id: str, body: SessionTenantUpdate):
    """Set or clear the tenant/customer name for an existing scan session."""
    _validate_session_id(session_id)
    engine = _get_engine()
    sessions = [s for s in engine.db_manager.list_sessions() if s.get("session_id") == session_id]
    if not sessions:
        raise HTTPException(status_code=404, detail=f"Session {session_id} not found.")
    from core.validation import sanitize_tenant_technician
    tenant = sanitize_tenant_technician(body.tenant)
    engine.db_manager.update_session_tenant(session_id, tenant)
    _invalidate_sessions_cache()
    return {"session_id": session_id, "tenant": tenant}


@app.patch("/sessions/{session_id}/technician", responses=_SESSION_RESPONSES)
async def update_session_technician(session_id: str, body: SessionTechnicianUpdate):
    """Set or clear the technician/operator name for an existing scan session."""
    _validate_session_id(session_id)
    engine = _get_engine()
    sessions = [s for s in engine.db_manager.list_sessions() if s.get("session_id") == session_id]
    if not sessions:
        raise HTTPException(status_code=404, detail=f"Session {session_id} not found.")
    from core.validation import sanitize_tenant_technician
    technician = sanitize_tenant_technician(body.technician)
    engine.db_manager.update_session_technician(session_id, technician)
    _invalidate_sessions_cache()
    return {"session_id": session_id, "technician": technician}


@app.get("/reports/{session_id}", responses=_SESSION_RESPONSES)
async def download_report_by_session(session_id: str):
    """Regenerate and download Excel report for the given session_id."""
    _validate_session_id(session_id)
    engine = _get_engine()
    path = engine.generate_final_reports(session_id)
    if path and Path(path).exists():
        return FileResponse(path, filename=Path(path).name, media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    raise HTTPException(status_code=404, detail=f"No data for session {session_id} or report generation failed.")


@app.get("/heatmap/{session_id}", responses=_SESSION_RESPONSES)
async def download_heatmap_by_session(session_id: str):
    """Regenerate report (if needed) and download heatmap PNG for the given session_id."""
    _validate_session_id(session_id)
    engine = _get_engine()
    path = engine.generate_final_reports(session_id)
    if not path or not Path(path).exists():
        raise HTTPException(status_code=404, detail=f"No data for session {session_id} or report generation failed.")
    out_dir = Path(path).parent
    # session_id already validated; safe for path segment (no ".." or slashes)
    safe_prefix = session_id[:12]
    heatmap_path = out_dir / f"heatmap_{safe_prefix}.png"
    if heatmap_path.exists():
        return FileResponse(heatmap_path, filename=heatmap_path.name, media_type="image/png")
    raise HTTPException(status_code=404, detail=f"Heatmap not available for session {session_id}. Run a scan and ensure findings exist.")


@app.get("/logs", responses=_NOT_FOUND_404)
async def download_latest_log():
    """
    Download the most recent audit_YYYYMMDD.log file from the current working directory.
    This file contains connection and finding logs for recent scan sessions.
    """
    log_dir = Path(".")
    candidates = sorted(log_dir.glob("audit_*.log"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        raise HTTPException(status_code=404, detail="No log files found.")
    latest = candidates[0]
    return FileResponse(latest, filename=latest.name, media_type="text/plain")


@app.get("/logs/{session_id}", responses=_SESSION_RESPONSES)
async def download_log_for_session(session_id: str):
    """
    Download the first audit_YYYYMMDD.log file that contains the given session_id.
    This allows linking scan sessions to their corresponding console/audit trace.
    Paths used are only from glob("audit_*.log"); session_id is not used in path expressions.
    """
    _validate_session_id(session_id)
    log_dir = Path(".")
    candidates = sorted(log_dir.glob("audit_*.log"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        raise HTTPException(status_code=404, detail="No log files found.")
    for p in candidates:
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if session_id in text:
            return FileResponse(p, filename=p.name, media_type="text/plain")
    raise HTTPException(status_code=404, detail=f"No log file contains session_id {session_id}.")


@app.post("/scan_database", responses=_RATE_LIMIT_429)
async def scan_database(config: DatabaseConfig, background_tasks: BackgroundTasks):
    """One-off scan of a single database (body: name, host, port, user, password, database, optional driver). Starts in background; returns session_id."""
    engine = _get_engine()
    if engine.is_running:
        raise HTTPException(status_code=409, detail="Audit already in progress.")
    # Apply same rate limiting as for full scans
    _check_rate_limit(source="scan_database")
    target = {
        "name": config.name,
        "type": "database",
        "driver": config.driver,
        "host": config.host,
        "port": config.port,
        "user": config.user,
        "pass": config.password,
        "database": config.database,
    }
    from core.session import new_session_id
    from core.validation import sanitize_tenant_technician
    session_id = new_session_id()
    tenant = sanitize_tenant_technician(config.tenant)
    technician = sanitize_tenant_technician(config.technician)
    engine.db_manager.set_current_session_id(session_id)
    engine.db_manager.create_session_record(
        session_id,
        tenant_name=tenant,
        technician_name=technician,
    )
    def run_one_target():
        engine._is_running = True
        try:
            engine._run_target(target)
        finally:
            engine._is_running = False
            engine.db_manager.finish_session(session_id, "completed")
    background_tasks.add_task(run_one_target)
    _invalidate_sessions_cache()
    return {"status": "started", "session_id": session_id}
